### ISSUE TITLE
Trying to run GDB on windows with zig-mingw built .exe fails

### ISSUE THREAD

**Issue by mundusnine** [lite-xl/lite-xl-ide#5]
When calling the `debugger:start-or-continue` command on windows on a .exe built with `zig cc -ggdb3` it opens the toggle window(stack trace etc.) then says starting and nothing happens:
![image](https://github.com/adamharrison/lite-xl-ide/assets/29337013/d482f709-2600-4973-a13e-5ef52d5204ec)

No log messages appear either.

### Miscellaneous info: 
zig cc generates separate symbol files even when using mingw-libc.

gdb is on PATH as I use [scoop](https://scoop.sh) to install it.

**Comment by mundusnine** [comment]
So after some searching, I found out that this isn't a windows issue, but more a pragtical issue. So the process in pragtical needs to have a second argument which is a table of process options:
![image](https://github.com/adamharrison/lite-xl-ide/assets/29337013/d9118944-4555-47f3-87f0-415935e77dc0)

and as we can see from the [process.c](https://github.com/pragtical/pragtical/blob/master/src/api/process.c#L609) in pragtical it is indeed needed.

Right now, it still doesn't debug even when passing the options table. Maybe I need to put a specific setting for the PIPE's since we are using gdb from command-line if I am not mistaken ?

**Comment by jgmdev** [comment]
The issue on Pragtical should be that since we incorporated https://github.com/lite-xl/lite-xl/pull/1455 the editor is no longer doing a chdir to the current root project directory. The solution would be to adapt lite-xl-ide plugin to account for this change or we restore the chdir to root project director to support older plugins.

As a workaround you may set `cwd` option to `core.root_project().path` and see if that works.

**Comment by adamharrison** [comment]
As this is an issue only in pragtical, I am closing this issue; when lite-xl transitions over to this system, this will be included as part of the standard plugin.
